# Generated by Django 4.2.7 on 2023-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.PositiveBigIntegerField()),
                ('titre_livre', models.CharField(max_length=150)),
                ('nom_auteurice', models.CharField(max_length=50)),
                ('prenom_auteurice', models.CharField(max_length=50)),
            ],
        ),
    ]
