# Generated by Django 4.2.7 on 2023-11-20 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_id_books_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='couverture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
